/* DO NOT EDIT THIS FILE */
/* This file is autogenerated by the text-database code generator */

#ifndef TOUCHGFX_TEXTKEYSANDLANGUAGES_HPP
#define TOUCHGFX_TEXTKEYSANDLANGUAGES_HPP

enum LANGUAGES
{
    GB,
    NUMBER_OF_LANGUAGES
};

enum TEXTS
{
    T___SINGLEUSE_2259,
    T___SINGLEUSE_AMQI,
    T___SINGLEUSE_FY12,
    T___SINGLEUSE_C1F3,
    T___SINGLEUSE_AE5B,
    NUMBER_OF_TEXT_KEYS
};

#endif // TOUCHGFX_TEXTKEYSANDLANGUAGES_HPP
