/* DO NOT EDIT THIS FILE */
/* This file is autogenerated by the text-database code generator */

#include <stdint.h>
#include <touchgfx/Unicode.hpp>

TEXT_LOCATION_FLASH_PRAGMA
KEEP extern const uint32_t indicesGb[] TEXT_LOCATION_FLASH_ATTRIBUTE;

// Remap all strings
TEXT_LOCATION_FLASH_PRAGMA
KEEP extern const uint32_t indicesGb[] TEXT_LOCATION_FLASH_ATTRIBUTE = {
    20, // T___SINGLEUSE_2259: "70%"
    16, // T___SINGLEUSE_AMQI: "40%"
    24, // T___SINGLEUSE_FY12: "80%"
    0,  // T___SINGLEUSE_C1F3: "55.6 %RH"
    9   // T___SINGLEUSE_AE5B: "27.1 C"
};
